# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/staillyd/Codes/cobb_angle/cobb_angle.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 707)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_msg = QtWidgets.QPlainTextEdit(self.groupBox)
        self.file_msg.setAutoFillBackground(True)
        self.file_msg.setReadOnly(True)
        self.file_msg.setBackgroundVisible(False)
        self.file_msg.setObjectName("file_msg")
        self.horizontalLayout.addWidget(self.file_msg)
        self.choose_file = QtWidgets.QPushButton(self.groupBox)
        self.choose_file.setObjectName("choose_file")
        self.horizontalLayout.addWidget(self.choose_file)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.origin_img = QtWidgets.QLabel(self.groupBox_2)
        self.origin_img.setAutoFillBackground(True)
        self.origin_img.setText("")
        self.origin_img.setObjectName("origin_img")
        self.gridLayout.addWidget(self.origin_img, 0, 0, 1, 1)
        self.result_image = QtWidgets.QLabel(self.groupBox_2)
        self.result_image.setAutoFillBackground(True)
        self.result_image.setText("")
        self.result_image.setObjectName("result_image")
        self.gridLayout.addWidget(self.result_image, 0, 1, 1, 1)
        self.show_text = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.show_text.setMaximumSize(QtCore.QSize(16777215, 100))
        self.show_text.setAutoFillBackground(True)
        self.show_text.setReadOnly(True)
        self.show_text.setBackgroundVisible(False)
        self.show_text.setCenterOnScroll(False)
        self.show_text.setObjectName("show_text")
        self.gridLayout.addWidget(self.show_text, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog)
        self.choose_file.clicked.connect(Dialog.on_choose_file)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "脊椎角度估算"))
        self.choose_file.setText(_translate("Dialog", "选择图片"))
